import type { Theme } from "components/ui/theme-provider";

export const defaultTheme: Theme = {
  name: "default",
  colors: {
    primary: "cyan",
    primaryForeground: "black",
    secondary: "blue",
    secondaryForeground: "white",
    accent: "magenta",
    accentForeground: "black",
    success: "green",
    successForeground: "black",
    warning: "yellow",
    warningForeground: "black",
    error: "red",
    errorForeground: "white",
    info: "blue",
    infoForeground: "white",
    background: "black",
    foreground: "white",
    muted: "gray",
    mutedForeground: "gray",
    border: "gray",
    focusRing: "cyan",
    selection: "blue",
    selectionForeground: "white",
  },
  spacing: {
    0: 0,
    1: 1,
    2: 2,
    3: 3,
    4: 4,
    6: 6,
    8: 8,
  },
  typography: {
    bold: false,
    sm: "sm",
    base: "base",
    lg: "lg",
    xl: "xl",
  },
  border: {
    style: "single",
    color: "gray",
    focusColor: "cyan",
  },
};
